ga_core_annonce:
    path:     /{page}
    defaults:  { _controller: GACoreBundle:Annonce:index, page: 1 }
    requirements: 
            page: \d*

ga_core_annonce_id:
    path:     /annonce/{id}
    defaults:  
        _controller: GACoreBundle:Annonce:view
        requirements:
        id: \d*

ga_core_annonce_id_admin:
    path:     /admin/annonce/view/{id}
    defaults:  
        _controller: GACoreBundle:Annonce:adminView
        requirements:
        id: \d*

ga_core_annonce_admin:
    path:   /admin/annonce
    defaults:
        _controller: GACoreBundle:Annonce:admin


ga_core_annonce_add:
    path:   /admin/annonce/add
    defaults:
        _controller: GACoreBundle:Annonce:add

ga_core_annonce_edit:
    path:   /admin/annonce/edit/{id}
    defaults:
        _controller: GACoreBundle:Annonce:edit

ga_core_annonce_delete:
    path:   /admin/annonce/delete/{id}
    defaults:
        _controller: GACoreBundle:Annonce:delete

ga_core_tournoi:
    path:     /tournoi/{id}
    defaults:
        _controller: GACoreBundle:Tournoi:view 
        requirements:
        id: \d*

ga_core_tournoi_admin:
    path:     /admin/tournoi
    defaults:
        _controller: GACoreBundle:Tournoi:admin

ga_core_tournoi_add:
    path:   /admin/tournoi/add
    defaults:
        _controller: GACoreBundle:Tournoi:add

ga_core_tournoi_edit:
    path:   /admin/tournoi/edit/{id}
    defaults:
        _controller: GACoreBundle:Tournoi:edit
        requirements:
        id: \d*

ga_core_tournoi_delete:
    path:   /admin/tournoi/delete/{id}
    defaults:
        _controller: GACoreBundle:Tournoi:delete
        requirements:
        id: \d*

ga_core_agenda:
    path:     /agenda
    defaults:
        _controller: GACoreBundle:Agenda:index 

ga_core_agenda_admin:
    path:     /admin/agenda
    defaults:
        _controller: GACoreBundle:Agenda:admin

ga_core_agenda_add:
    path:     /admin/agenda/add
    defaults:
        _controller: GACoreBundle:Agenda:add

ga_core_agenda_edit:
    path:     /admin/agenda/edit
    defaults:
        _controller: GACoreBundle:Agenda:edit 

ga_core_agenda_delete:
    path:     /admin/agenda/delete
    defaults:
        _controller: GACoreBundle:Agenda:delete

ga_core_static_presentation:
    path:    /presentation
    defaults:
        _controller: GACoreBundle:Static:presentation

ga_core_static_organigramme:
    path:    /organigramme
    defaults:
        _controller: GACoreBundle:Static:organigramme

ga_core_static_clubs:
    path:    /clubs
    defaults:
        _controller: GACoreBundle:Static:clubs

ga_core_static_tarif:
    path:    /tarif
    defaults:
        _controller: GACoreBundle:Static:tarif

ga_core_admin:
    path:    /admin
    defaults:
        _controller: GACoreBundle:Static:admin

ga_core_ressource_add_tournoi:
    path:    /admin/ressource/add/tournoi/{id}/{type}
    defaults:
        _controller: GACoreBundle:Ressource:addTournoi

ga_core_ressource_edit_tournoi:
    path:    /admin/ressource/edit/tournoi/{id}/{type}/{idR}
    defaults:
        _controller: GACoreBundle:Ressource:editTournoi

ga_core_ressource_delete_tournoi:
    path:    /admin/ressource/delete/tournoi/{id}/{type}/{idR}
    defaults:
        _controller: GACoreBundle:Ressource:deleteTournoi

ga_core_ressource_add_annonce:
    path:    /admin/ressource/add/annonce/{id}/{type}
    defaults:
        _controller: GACoreBundle:Ressource:addAnnonce

ga_core_ressource_edit_annonce:
    path:    /admin/ressource/edit/annonce/{id}/{type}/{idR}
    defaults:
        _controller: GACoreBundle:Ressource:editAnnonce

ga_core_ressource_delete_annonce:
    path:    /admin/ressource/delete/annonce/{id}/{type}/{idR}
    defaults:
        _controller: GACoreBundle:Ressource:deleteAnnonce

ga_core_ressource_add_ronde:
    path:    /admin/ressource/add/tournoi/{id}/{type}/{num}
    defaults:
        _controller: GACoreBundle:Ressource:addRonde

ga_core_ressource_edit_ronde:
    path:    /admin/ressource/edit/annonce/{id}/{type}/{num}/{idR}
    defaults:
        _controller: GACoreBundle:Ressource:editRonde

ga_core_ressource_delete_ronde:
    path:    /admin/ressource/delete/annonce/{id}/{type}/{num}/{idR}
    defaults:
        _controller: GACoreBundle:Ressource:deleteRonde

ga_core_tournoi_id_admin:
    path:     /admin/tournoi/view/{id}
    defaults:
        _controller: GACoreBundle:Tournoi:adminView
        requirements:
        id: \d*

