ga_core_annonce:
    path:     /{page}
    defaults:  
        _controller: GACoreBundle:Annonce:index 
        
    requirements:
        page: \d*

ga_core_annonce_id:
    path:     /news/{id}
    defaults:  
        _controller: GACoreBundle:Annonce:view
        requirements:
        id: \d*

ga_core_annonce_add:
    path:   /admin/news/add
    defaults:
        _controller: GACoreBundle:Annonce:add

ga_core_annonce_edit:
    path:   /admin/news/edit/{id}
    defaults:
        _controller: GACoreBundle:Annonce:edit

ga_core_annonce_delete:
    path:   /admin/news/delete/{id}
    defaults:
        _controller: GACoreBundle:Annonce:delete

ga_core_tournoi:
    path:     /tournoi/{id}
    defaults:
        _controller: GACoreBundle:Tournoi:view 
        requirements:
        id: \d*

ga_core_tournoi_add:
    path:   /admin/tournoi/add
    defaults:
        _controller: GACoreBundle:Tournoi:add

ga_core_tournoi_edit:
    path:   /admin/tournoi/edit/{id}
    defaults:
        _controller: GACoreBundle:Tournoi:edit
        requirements:
        id: \d*

ga_core_tournoi_delete:
    path:   /admin/tournoi/delete/{id}
    defaults:
        _controller: GACoreBundle:Tournoi:delete
        requirements:
        id: \d*

ga_core_agenda:
    path:     /agenda
    defaults:
        _controller: GACoreBundle:Agenda:index 

ga_core_agenda_add:
    path:     /admin/agenda/add
    defaults:
        _controller: GACoreBundle:Agenda:add

ga_core_agenda_edit:
    path:     /admin/agenda/edit
    defaults:
        _controller: GACoreBundle:Agenda:edit 

ga_core_agenda_delete:
    path:     /admin/agenda/delete
    defaults:
        _controller: GACoreBundle:Agenda:delete

ga_core_static_presentation:
    path:    /presentation
    defaults:
        _controller: GACoreBundle:Static:presentation

ga_core_static_admin:
    path:    /admin
    defaults:
        _controller: GACoreBundle:Static:admin

ga_core_static_organigramme:
    path:    /organigramme
    defaults:
        _controller: GACoreBundle:Static:organigramme

ga_core_static_clubs:
    path:    /clubs
    defaults:
        _controller: GACoreBundle:Static:clubs

ga_core_static_tarif:
    path:    /tarif
    defaults:
        _controller: GACoreBundle:Static:tarif