services:
#    ga_core.example:
#        class: GA\CoreBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    ga_core.lien_controller:
        class: GA\CoreBundle\Controller\LienController
        arguments: ['@templating']

    ga_core.test_controller:
        class: GA\CoreBundle\Controller\TestaController

    ga_core.brochure_uploader:
        class: GA\CoreBundle\FileUploader\FileUploader
        arguments: ['%brochures_directory%']