services:
#    ga_core.example:
#        class: GA\CoreBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    ga_core.lien_controller:
        class: GA\CoreBundle\Controller\LienController
        arguments: ['@templating']

    ga_core.test_controller:
        class: GA\CoreBundle\Controller\TestaController

    ga_core.resultat_uploader:
        class: GA\CoreBundle\FileUploader\FileUploader
        arguments: ['%resultat_directory%']

    ga_core.resultat_listener:
        class: GA\CoreBundle\EventListener\ResultatUploadListener
        arguments: ['@ga_core.resultat_uploader']
 
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postLoad }
            - { name: doctrine.event_listener, event: preRemove}
            - { name: doctrine.event_listener, event: postRemove}

    core.twig_extension:
        class:    GA\CoreBundle\Twig\CoreExtension
        public:    false
        tags:
                - { name:    twig.extension}

    ga_core.affiche_uploader:
        class: GA\CoreBundle\FileUploader\FileUploader
        arguments: ['%affiche_directory%']

    ga_core.affiche_listener:
        class: GA\CoreBundle\EventListener\AfficheUploadListener
        arguments: ['@ga_core.affiche_uploader']
 
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: preRemove}
            - { name: doctrine.event_listener, event: postRemove}
