services:
#    ga_core.example:
#        class: GA\CoreBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    ga_core.lien_controller:
        class: GA\CoreBundle\Controller\LienController
        arguments: ['@templating']

    ga_core.test_controller:
        class: GA\CoreBundle\Controller\TestaController

    ga_core.brochure_uploader:
        class: GA\CoreBundle\FileUploader\FileUploader
        arguments: ['%brochures_directory%']

    ga_core.brochure_listener:
        class: GA\CoreBundle\EventListener\BrochureUploadListener
        arguments: ['@ga_core.brochure_uploader']
 
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postLoad }
            - { name: doctrine.event_listener, event: preRemove}
            - { name: doctrine.event_listener, event: postRemove}