<?php

namespace GA\CoreBundle\Repository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends \Doctrine\ORM\EntityRepository
{
	public function findListeAnnoncePost()
	{
		$qb = $this->createQueryBuilder('a');
		
		$qb	->where('a.publication = :publication')
					->setParameter('publication', 1);

		$qb->orderBy('a.dateCreat', 'DESC');

		return $qb ->getQuery()
										 ->getResult();
	}
	
	public function findAllInv()
	{
		$qb = $this->createQueryBuilder('a');

		$qb->orderBy('a.dateCreat', 'DESC');

		return $qb ->getQuery()
										 ->getResult();
	}
}
