<?php

namespace GA\CoreBundle\Repository;

/**
 * AfficheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{
}
