<?php

namespace GA\CoreBundle\Repository;

/**
 * ManyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManyRepository extends \Doctrine\ORM\EntityRepository
{
}
