<?php

namespace GA\CoreBundle\Repository;

/**
 * OneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OneRepository extends \Doctrine\ORM\EntityRepository
{
}
