<?php

namespace GA\CoreBundle\Repository;

/**
 * RondeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RondeRepository extends \Doctrine\ORM\EntityRepository
{
	public function findRondePoster()
	{
		$qb = $this->createQueryBuilder('r')
		->select('r.id','r.dateEvent','r.poste')
		->where('r.poste = :poste')
			->setParameter(':poste', false)
		;
		
		
		$end = new \Datetime ;
		$end ->add(new \DateInterval('P10D'));
		
    $qb
      ->andWhere('r.dateEvent < :end')
      ->setParameter('end', $end) 
    ;
			
		
		return $qb->getQuery()->getArrayResult();
		}
		
	public function findRondeBySaison(Array $saison)
	{
		$qb = $this->createQueryBuilder('r');

   
    $qb
      ->join('r.tournois', 't')
      ->addSelect('t')
    ;

    $qb->where($qb->expr()->in('t.saison', $saison));
    
    return $qb
      ->getQuery()
      ->getResult();
			
	}
}
