<?php

namespace GA\CoreBundle\Repository;

/**
 * RondeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RondeRepository extends \Doctrine\ORM\EntityRepository
{
}
