<?php

namespace GA\CoreBundle\Repository;

/**
 * TournoiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TournoiRepository extends \Doctrine\ORM\EntityRepository
{
	public function findListeSaison($jeune)
	{
		$qb = $this->createQueryBuilder('t')->select('t.saison')->distinct(true);
		
		$qb->where('t.jeune = :jeune')
							->setParameter('jeune', $jeune)
		;
		
		return $qb->getQuery()->getArrayResult();
		
	}
	
	public function findTournoiBySaison($saison)
	{
		$qb = $this->createQueryBuilder('t')->select('t.id','t.nom');
		
		$qb->where('t.saison = :saison')
								->setParameter('saison', $saison)
		;
		
		return $qb->getQuery()->getArrayResult();
		}
}


