<?php

namespace GA\CoreBundle\Repository;

/**
 * TournoiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TournoiRepository extends \Doctrine\ORM\EntityRepository
{
	public function findListeSaison($jeune)
	{
		$qb = $this->createQueryBuilder('t')->select('t.saison')->distinct(true);
		
		$qb->where('t.jeune = :jeune')
							->setParameter('jeune', $jeune)
		;
		
		return $qb->getQuery()->getArrayResult();
		
	}
	
	public function findTournoiBySaisonAdulte($saison)
	{
		$qb = $this->createQueryBuilder('t')->select('t.id','t.nom');
		
		$qb->where('t.saison = :saison')
								->setParameter('saison', $saison)
					->andwhere('t.jeune = :jeune')
								->setParameter('jeune', false)
		;
		
		return $qb->getQuery()->getArrayResult();
		}
		
		public function findTournoiBySaisonJeune($saison)
	{
		$qb = $this->createQueryBuilder('t')->select('t.id','t.nom');
		
		$qb->where('t.saison = :saison')
								->setParameter('saison', $saison)
					->andwhere('t.jeune = :jeune')
								->setParameter('jeune', true)
		;
		
		return $qb->getQuery()->getArrayResult();
		}
		
		public function getIdLien($id)
		{
			$qb = $this->createQueryBuilder('t');
			
			$qb ->innerJoin('t.lien', 'l')
						->addSelect('l');
						
			return $qb->getQuery()->getArrayResult();
			
		}
		
		public function findTournoiByRonde(Array $ronde)
		{
			$qb = $this->createQueryBuilder('t');

    // On fait une jointure avec l'entité Category avec pour alias « c »
    $qb
      ->join('t.rondes', 'r')
      ->addSelect('r')
    ;

    // Puis on filtre sur le nom des catégories à l'aide d'un IN
    $qb->where($qb->expr()->in('r.id', $ronde));
    // La syntaxe du IN et d'autres expressions se trouve dans la documentation Doctrine

    // Enfin, on retourne le résultat
    return $qb
      ->getQuery()
      ->getResult();
		}
}


